### PR TITLE
unreal_asset: Better ByteProperty representation

### PR DESCRIPTION
**Pull request by bananaturtlesandwich**
The ByteType::Long was actually an fname so converted it and also used rust idiomatic enums
I'm positive it works I tested it

### CODE REVIEW

**Comment by localcc** [comment]
This is fixed by completely porting over the new byte parsing code from UAssetAPI in the upstream merge branch, it's going to be hopefully merged into main soon.

**Comment by konsti219** [comment]
Stop constantly creating new forks for each PR! It clogs up our webhooks.

**Comment by bananaturtlesandwich** [comment]
Sorry didn't know you had webhooks

**Comment by bananaturtlesandwich** [comment]
I'm probably not going to make another PR for a while so I'll delete my fork now

**Pull request closed without merging**
